version: '3.8'

networks:
  docker_internal:
    external: true

services:
  stockmarket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockmarket_ai
    ports:
      - "8501:8501"
    volumes:
      - stockmarket_db:/app/db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - docker_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  stockmarket_db:
    driver: local